# Generated by Django 3.1 on 2020-09-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentirinha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
