version: '3'
services:
  mentirinha:
    build: .
    command: uwsgi --ini uwsgi.ini
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file: mentirinha.env
    depends_on: [redis]
  counter:
    build: .
    command: python manage.py counter_updater
    restart: unless-stopped
    env_file: mentirinha.env
    depends_on: [redis]
  redis:
    image: redis:6.2.5